field: 77af5a62-d057-494a-91ac-9edf65b6b266 # Content Builder
fieldLayouts:
  7d8c40f9-257c-41b4-8747-551f180cacc5:
    tabs:
      -
        elements:
          -
            fieldUid: 5bed279a-5360-4e96-b92e-3153c98bff40 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5bed279a-5360-4e96-b92e-3153c98bff40: # Copy
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: button
    instructions: ''
    name: Copy
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Site.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
handle: callToAction
name: 'Call To Action'
sortOrder: 1
