field: 77af5a62-d057-494a-91ac-9edf65b6b266 # Content Builder
fieldLayouts:
  7d8c40f9-257c-41b4-8747-551f180cacc5:
    tabs:
      -
        elements:
          -
            fieldUid: 5bed279a-5360-4e96-b92e-3153c98bff40 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a71662d0-b947-40fe-9aee-693197d4445b
            warning: null
            width: 100
        name: Content
        uid: d76b4b4a-101d-4508-8153-84c7205cd9a3
fields:
  5bed279a-5360-4e96-b92e-3153c98bff40: # Copy
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: button
    instructions: null
    name: Copy
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Site.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
handle: callToAction
name: 'Call To Action'
sortOrder: 1
