fieldLayouts:
  c626b1d8-1909-423a-a161-eda975647216:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4a9c3468-247d-4f5a-9bb4-cc13ba9aaa61
            warning: null
            width: 100
          -
            fieldUid: 56f86cc6-5713-447f-8b10-e53f06ef42eb # Hide from Nav
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f733cb5-f471-4dff-b2a3-d81a2354ba71
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 85a4a23d-3725-49a3-9650-918f3be12037
          -
            fieldUid: ab8abc7e-2a4d-4858-98ea-9a6954a434da # Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43d8cb47-c827-4bf1-9813-485c81b5c326
            warning: null
            width: 100
          -
            heading: 'Main Content'
            type: craft\fieldlayoutelements\Heading
            uid: b16c683b-ef39-4e18-86d3-fc3566be5c73
          -
            fieldUid: 95ce0179-ac46-4ecb-910c-aa91c7a07961 # Summary
            instructions: null
            label: Copy
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43ae12e0-d1f6-4042-b214-32aeabadd0de
            warning: null
            width: 100
        name: Content
        uid: 02bd7ec5-b7cd-4277-9993-5e39613b939a
      -
        elements:
          -
            fieldUid: 149ec41c-d6de-4ae5-84db-08d285801dd1 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0280f63c-8003-4627-acde-ccde741de390
            warning: null
            width: 100
        name: SEO
        uid: 26cb98cc-1949-467c-8b80-02a8b8ef608f
handle: contactPage
hasTitleField: true
name: 'Contact Page'
section: 666b31c2-d6d5-4e80-b9aa-f57b66d5b54a # Pages
sortOrder: 4
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
