fieldLayouts:
  171a213e-9b33-49e7-bf1d-8056ef4d5c12:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            style: tip
            tip: 'Summary should only be 2-3 sentences. Image will appear on listing page'
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: b2f53aa5-81a3-466c-af2d-e30dab4ed3d8 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 95ce0179-ac46-4ecb-910c-aa91c7a07961 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: fbdde691-0df2-4e8e-b1a8-61a1f555fd0e # News Categories
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: 'Main Content'
            type: craft\fieldlayoutelements\Heading
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 149ec41c-d6de-4ae5-84db-08d285801dd1 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: default
hasTitleField: true
name: Default
section: 9c12e5ad-18e9-498f-bf50-489513409007 # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
