fieldLayouts:
  8f880d21-2d24-4e77-b149-cd95cb26961c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5f6b0ffc-3351-4869-b4a4-11aee4c1c5e9
            warning: null
            width: 100
          -
            style: tip
            tip: 'No Fields yet'
            type: craft\fieldlayoutelements\Tip
            uid: 1d3caec2-b528-4f62-9db5-da38ccc0b70d
        name: Content
        uid: 00dcba48-c8e6-436c-88cf-4362f6b375cc
      -
        elements:
          -
            fieldUid: 149ec41c-d6de-4ae5-84db-08d285801dd1 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e7499cf-96a5-4586-90e6-9eacb5fdbda7
            warning: null
            width: 100
        name: SEO
        uid: 5c2081a7-07bd-42f2-8c3d-66f1639b113a
handle: newsListing
hasTitleField: true
name: 'News Listing'
section: 666b31c2-d6d5-4e80-b9aa-f57b66d5b54a # Pages
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
