fieldLayouts:
  763d8c69-2e2f-4452-9c19-5408b26d3e08:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 56f86cc6-5713-447f-8b10-e53f06ef42eb # Hide from Nav
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: ab8abc7e-2a4d-4858-98ea-9a6954a434da # Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: 'Main Content'
            type: craft\fieldlayoutelements\Heading
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 149ec41c-d6de-4ae5-84db-08d285801dd1 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: pages
hasTitleField: true
name: Pages
section: 666b31c2-d6d5-4e80-b9aa-f57b66d5b54a # Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
