defaultPlacement: end
fieldLayouts:
  33ffecde-4b2e-4645-ad54-3c15b2967fcc:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: newsCategories
name: 'News Categories'
siteSettings:
  1a78d395-d81a-4b77-8da7-30a49123bbee: # English
    hasUrls: false
    template: null
    uriFormat: null
  b9fdef79-5b63-4932-a9aa-8d18f937e6d9: # Français
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: a23aa2ea-1f11-4fd2-b2ea-e420d27e959d
