fieldLayouts:
  eb53ac7e-fc3b-4522-a428-91addf2ec44f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fs: userGuide
handle: userGuide
hasUrls: true
name: 'User Guide'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: $GUIDE_BASE_URL
