columnSuffix: null
contentColumnType: string
fieldGroup: ef8cc244-dfa8-41b1-945d-cb673ae71824
handle: hero
instructions: ''
name: Hero
searchable: false
settings:
  contentTable: '{{%matrixcontent_hero}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
