contentColumnType: string
fieldGroup: ca4cf186-4f48-488c-adbc-d38eba9d2533
handle: userGuide
instructions: ''
name: 'User Guide'
searchable: false
settings:
  contentTable: '{{%matrixcontent_userguide}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
