dateModified: 1618925173
email:
  fromEmail: $SYSTEM_EMAIL
  fromName: $SENDER_NAME
  replyToEmail: $FROM_EMAIL
  template: null
  transportSettings:
    encryptionMethod: ''
    host: $EMAIL_HOSTNAME
    password: $EMAIL_PASSWORD
    port: $EMAIL_PORT
    timeout: '10'
    useAuthentication: '1'
    username: $EMAIL_USERNAME
  transportType: craft\mail\transportadapters\Smtp
plugins:
  environment-label:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-toolbox:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 0F9VOPZ558WMQISLHBLYMB51
    schemaVersion: 3.0.9
  templatecomments:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  usermanual:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
    settings:
      pluginNameOverride: 'User Manual'
      section: '3'
      templateOverride: _user-guide/_entry
system:
  edition: pro
  live: true
  name: $SITE_NAME
  retryDuration: null
  schemaVersion: 3.6.8
  timeZone: America/Toronto
