description: ''
handle: siteAdmin
name: 'Site Admin'
permissions:
  - accessplugin-seomatic
  - accessplugin-usermanual
  - accesscp
  - 'publishentries:722083b8-e7bc-4d95-b4dd-3473680b72a7'
  - 'publishpeerentrydrafts:722083b8-e7bc-4d95-b4dd-3473680b72a7'
  - 'deletepeerentrydrafts:722083b8-e7bc-4d95-b4dd-3473680b72a7'
  - 'editpeerentrydrafts:722083b8-e7bc-4d95-b4dd-3473680b72a7'
  - 'editentries:722083b8-e7bc-4d95-b4dd-3473680b72a7'
  - 'saveassetinvolume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670'
  - 'createfoldersinvolume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670'
  - 'deletefilesandfoldersinvolume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670'
  - 'replacefilesinvolume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670'
  - 'editimagesinvolume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670'
  - 'editpeerfilesinvolume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670'
  - 'replacepeerfilesinvolume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670'
  - 'deletepeerfilesinvolume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670'
  - 'editpeerimagesinvolume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670'
  - 'viewpeerfilesinvolume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670'
  - 'viewvolume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670'
  - 'utility:system-report'
  - 'utility:asset-indexes'
  - 'utility:db-backup'
  - 'seomatic:dashboard'
  - 'seomatic:global-meta:general'
  - 'seomatic:global-meta:twitter'
  - 'seomatic:global-meta:facebook'
  - 'seomatic:global-meta:robots'
  - 'seomatic:global-meta'
  - 'seomatic:content-meta:general'
  - 'seomatic:content-meta:twitter'
  - 'seomatic:content-meta:facebook'
  - 'seomatic:content-meta:sitemap'
  - 'seomatic:content-meta'
  - 'seomatic:site-settings:identity'
  - 'seomatic:site-settings:social'
  - 'seomatic:site-settings:sitemap'
  - 'seomatic:site-settings'
  - 'seomatic:tracking-scripts:googleanalytics'
  - 'seomatic:tracking-scripts:gtag'
  - 'seomatic:tracking-scripts:googletagmanager'
  - 'seomatic:tracking-scripts'
