enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  1a78d395-d81a-4b77-8da7-30a49123bbee:
    enabledByDefault: true
    hasUrls: true
    template: homepage/_entry
    uriFormat: homepage
type: single
